name: instances-updater

on:
  schedule:
    - cron: '10 22 */3 * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: get repo content
        uses: actions/checkout@v3.3.0
        
      - name: setup python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.8'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests colorama
      
      - name: run script
        run: python instances.py
      
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update instances" -a || :
      
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
